services:

  queue:
    image: rabbitmq:4-management
    ports:
      - 5999:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=toto
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 8s
      timeout: 30s
      retries: 3

  mailer:
    image: canals/php:8.2
    container_name: mailer.toubeelib
    volumes:
      - ./mailer:/var/www/html
    working_dir: /var/www/html
    env_file: 
      - ./mailer.env
      - ./amqp.env
    command: php mailer.php
    depends_on:
      queue:
        condition: service_healthy

  # service api.toubeelib : api pour la prise de rdv
  gateway.toubeelib:
    image: canals/php:8.2
    # build:
    #   context: build
    #   dockerfile: 8.2.dockerfile
    env_file: ./toubeelib.env
    container_name: gateway_toubeelib
    ports:
      - '6081:80'
    volumes:
      - ./gateway:/var/www
      - ./gateway/public:/var/www/html
    working_dir: /var/www
    depends_on:
      queue:
        condition: service_healthy
    # command: php -S 0.0.0.0:80 -t /var/php/public

    # service toubeelib.db : base de données postgresql
  toubeelib.auth.db:
    image: 'postgres:latest'
    env_file: ./toubeelibauthdb.env
    ports:
      - $PORT_AUTH_BD:5432
    volumes:
      - ./app/sql:/var/sql'

# micro service praticien 

   # service api.toubeelib : api pour la prise de rdv
  api.toubeelib.praticiens:
    image: canals/php:8.2
    # build:
    #   context: build
    #   dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib.env
    container_name: api_toubeelib_praticien
    ports:
      - $PORT_PRATICIEN:80
    volumes:
      - ./app-praticiens:/var/www
      - ./app-praticiens/public:/var/www/html
      - ./app-praticiens/sql:/var/sql
    working_dir: /var/www
    depends_on:
      - toubeelib.praticiens.db
    # command: php -S 0.0.0.0:80 -t /var/php/public

  api.toubeelib.rdv:
    image: canals/php:8.2
    container_name: api_toubeelib_rdv
    env_file:
      - ./mailer.env
      - ./amqp.env
      - ./toubeelib.env
    ports:
      - $PORT_RDV:80
    volumes:
      - ./app-rdv:/var/www
      - ./app-rdv/public:/var/www/html
      - ./app-rdv/sql:/var/sql
    working_dir: /var/www
    depends_on:
      - toubeelib.rdv.db
    # command: php -S 0.0.0.0:80 -t /var/php/public

  toubeelib.rdv.db:
    image: 'postgres:latest'
    env_file:
      - ./toubeelibdb.env
    container_name: toubeelib.rdv.db
    ports:
      - $PORT_RDV_BD:5432
    volumes:
      - ./app/sql:/var/sql'

  toubeelib.praticiens.db:
    image: 'postgres:latest'
    env_file: ./toubeelibdb.env
    container_name: toubeelib.praticiens.db
    ports:
      - $PORT_PRATICIEN_BD:5432
    volumes:
      - ./app/sql:/var/sql'
    

  api.toubeelib.auth:
    image: canals/php:8.2
    container_name: api_toubeelib_auth
    ports:
      - $PORT_AUTH:80
    volumes:
      - ./app-auth:/var/www
      - ./app-auth/public:/var/www/html
      - ./app-auth/sql:/var/sql
    working_dir: /var/www
    env_file: ./toubeelib.env
    depends_on:
      - toubeelib.auth.db

  mailcatcher:
    build:
      context: ./build
      dockerfile: mailcatcher.Dockerfile
    ports:
      - $PORT_MAILCATCHER:1080
      - 1025:1025
