networks:
  toubeelib.net:
    driver: bridge
services:


  # service api.toubeelib : api pour la prise de rdv
  gateway.toubeelib:
    image: canals/php:8.2-cli
    # build:
    #   context: build
    #   dockerfile: 8.2.dockerfile
    env_file: ./toubeelib.env
    container_name: gateway_toubeelib
    ports:
      - '6081:80'
    volumes:
      - ./gateway:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  # service api.toubeelib : api pour la prise de rdv
  api.toubeelib:
    image: canals/php:8.2-cli
    # build:
    #   context: build
    #   dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib.env
    container_name: api_toubeelib_gt
    ports:
      - $PORT_API:80
    volumes:
      - ./app:/var/php
      - ./sql:/var/sql
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

    # service toubeelib.db : base de données postgresql
  toubeelib.auth.db:
    image: 'postgres:latest'
    env_file: ./toubeelibauthdb.env
    ports:
      - $PORT_AUTH:5432
    networks:
      - toubeelib.net
    volumes:
      - ./app/sql:/var/sql'

  toubeelib.db:
    image: 'postgres:latest'
    env_file: ./toubeelibdb.env
    ports:
      - $PORT_DB:5432
    networks:
      - toubeelib.net
    volumes:
      - ./app/sql:/var/sql'
  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - $PORT_ADMINER:8080
    networks:
      - toubeelib.net


# micro service praticien 

   # service api.toubeelib : api pour la prise de rdv
  api.toubeelib.praticiens:
    image: canals/php:8.2-cli
    # build:
    #   context: build
    #   dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib.env
    container_name: api_toubeelib_praticien
    ports:
      - $PORT_PRATICIEN:80
    volumes:
      - ./app-praticiens:/var/php
      - ./app-praticiens/sql:/var/sql
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.praticiens.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  api.toubeelib.rdv:
    image: canals/php:8.2-cli
    container_name: api_toubeelib_rdv
    ports:
      - $PORT_RDV:80
    volumes:
      - ./app-rdv:/var/php
      - ./app-rdv/sql:/var/sql
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.rdv.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  toubeelib.rdv.db:
    image: 'postgres:latest'
    env_file: ./toubeelibdb.env
    container_name: toubeelib.rdv.db
    ports:
      - $PORT_RDV_BD:5432
    networks:
      - toubeelib.net
    volumes:
      - ./app/sql:/var/sql'

  toubeelib.praticiens.db:
    image: 'postgres:latest'
    env_file: ./toubeelibdb.env
    container_name: toubeelib.praticiens.db
    ports:
      - $PORT_PRATICIEN_BD:5432
    networks:
      - toubeelib.net
    volumes:
      - ./app/sql:/var/sql'
